[build]
  command = "npm run build"  
  publish = ".next"  

[build.environment]
  JWT_SECRET = "ThisIsTheSecureKey1234567890"  

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Credentials = "true"